//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Candidaturas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidato
    {
        public int UserID { get; set; }
        public int Numero { get; set; }
        public string Edicao { get; set; }
        public bool Sincronizado { get; set; }
    
        public virtual Edicao Edicao1 { get; set; }
        public virtual User User { get; set; }
    }
}
