//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Candidaturas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DadosPessoai
    {
        public string NomeColoquial { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        public string Nomes { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        public string Apelidos { get; set; }
        public string NomePai { get; set; }
        public string NomeMae { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        public string NDI { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        public string TipoDocID { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        public string Genero { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        public string EstadoCivil { get; set; }
        public string Nacionalidade { get; set; }
        public string DistritoNatural { get; set; }
        public string ConcelhoNatural { get; set; }
        public string FreguesiaNatural { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        public string Morada { get; set; }
        public string Localidade { get; set; }
        public int UserId { get; set; }
        public int ID { get; set; }
        public string RepFinNIF { get; set; }
        public string CCDigitosControlo { get; set; }
        public string NSegSoc { get; set; }
        public string NIF { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        public string DistritoMorada { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        public string ConcelhoMorada { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        public string FreguesiaMorada { get; set; }
        public string Telefone { get; set; }

        [Required(ErrorMessage = "Campo Obrigatório")]
        public string CodigoPostal4Dig { get; set; }
        public string CodigoPostal3Dig { get; set; }
        public Nullable<System.DateTime> DataCriacao { get; set; }
        public Nullable<System.DateTime> DataUltimaAtualizacao { get; set; }
    }
}
